# Site settings
title: Yusuf's blog
email: me@yusufhm.info
description: "Mauritian Drupal Developer based in Sydney. Occasionally dabbles in some amount of system administration (Ubuntu Linux). This site serves as a log book of a kind, to keep track of important things."
baseurl: ""
url: "http://www.yusufhm.info"

# Build settings
markdown: kramdown
permalink: pretty
